### ISSUE TITLE
Demo for angular not working on android version 4.0

### ISSUE THREAD

**Issue by ghost** [NathanWalker/nativescript-shimmer#3]

**Comment by tahir-jamil** [comment]
demo is not working 
```
CONSOLE ERROR file:///app/tns_modules/@angular/core/./bundles/core.umd.js:1052:24: ERROR Error: Uncaught (in promise): TypeError: Could not load view for: Shimmer.Error: Could not find module 'nativescript-shimmer'. Computed path '/Users/m.tahir/Library/Developer/CoreSimulator/Devices/E175A09A-7E5E-4217-8B9F-EF7D6FA378D1/data/Containers/Bundle/Application/A82130F7-5FFE-4919-8A4C-A36B647050AE/demong.app/app/tns_modules/nativescript-shimmer'.
getViewClass@file:///app/tns_modules/nativescript-angular/element-registry.js:86:28
createView@file:///app/tns_modules/nativescript-angular/view-util.js:195:56
createElement@file:///app/tns_modules/nativescript-angular/renderer.js:106:40
createElement@file:///app/tns_modules/@angular/core/./bundles/core.umd.js:13595:62
```

**Comment by ibnYusrat** [comment]
I think you will need to install nativescript shimmer for this.
